#!/usr/bin/env sh

if [ -d /etc/X11/xinit/xinitrc.d ];then
	for f in /etc/X11/xinit/xinitrc.d/?*;do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

defaultserverargs="-nolisten tcp"

# cleans old serverauths
/usr/local/bin/clean-serverauth

# start user dbus session
if which dbus-launch >/dev/null && test -z "${DBUS_SESSION_BUS_ADDRESS}"; then
	eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

# disables turning idle screen off
#xset s off &

#when idle turn screen off after 15min
#xset -dpms &

# pipewire sound system
#/usr/bin/pipewire &
/usr/bin/gentoo-pipewire-launcher &

#exec dbus-launch --exit-with-session i3

exec i3

