# to make sure any edits are valid run
# flexget -c ~/.config/flexget/config.yml check

schedules:
  - tasks: '*'
    interval:
      # minutes: 1
      hours: 1

templates:
  global:
    torrent_scrub: rtorrent

  anime:
    include: anime.yml
    # bind download location for docker container
    download: /downloads
    content_filter:
      require:
        - '*.mkv'
    regexp:
      reject:
        # erai v0
        - v0
        # low resolution
        - 480p
        - 720p
        # should block all non english
        - \b(s|d)ub(s|bed|lado|titulado)?\b
        - \bhc\b
        - \bdual\b
        - \b3d\b
        - \bfre(nch)?\b
        - \bita(lian)?\b
        - \bspa(nish)?\b
        - \bger(man)?\b
        - \bcastellano\b
        - \brus(sian)?\b
    quality:
      - 1080p

tasks:
  Anime:
    priority: 1
    rss: https://nyaa.si/?page=rss&c=1_2&f=0
    template: anime
    # verify_ssl_certificates: yes

