#to make sure edits are valid
#$flexget check
schedules:
  - tasks: 'Anime'
    interval:
      #minutes: 1
      hours: 1

templates:
  global:
    torrent_scrub: rtorrent
    domain_delay:
      nyaa.si: 5 seconds
      nyaa.pantsu.cat: 5 seconds
      anidex.info: 5 seconds
    verify_ssl_certificates: yes
    content_filter:
      require:
        - '*.mkv'
    no_entries_ok: yes

#anime series list
  anime-airing:
    include: anime.yml
    download: /mnt/cache/anime/watch
    regexp:
      reject:
        #should block all non english
        - 480p
        - 720p
        - \b(s|d)ub(s|bed|lado|titulado)?\b
        - \bhc\b
        - \bdual\b
        - \b3d\b
        - \bfre(nch)?\b
        - \bita(lian)?\b
        - \bspa(nish)?\b
        - \bger(man)?\b
        - \bcastellano\b
        - \brus(sian)?\b
    quality:
      - 1080p

#tasks to run
tasks:
  Anime:
    priority: 10
    template:
      - anime-airing
    inputs:
    #  - rss: https://anidex.info/rss/?cat=1&lang_id=1
      - rss: https://nyaa.si/?page=rss&cats=1_37&filter=2
      - rss: https://nyaa.si/?page=rss&c=1_2&f=0
    #  - rss: https://nyaa.pantsu.cat/feed?
